Added condition codes to oocd, oohk and oorp

diff --git a/oocd b/oocd
--- a/oocd
+++ b/oocd
@@ -1,13 +1,17 @@
 #!/bin/bash
 # ==================================================================================
-# /usr/local/bin/oocdnew
+# /usr/local/bin/oocd
 # ==================================================================================
 # Change this variable to the directory where the configuration files are stored.  =
 # Normally this would be: oo_confpath="/etc/oos"                                   =
 # The quotes are needed in case there are spaces in the directory name.            =
 oo_confpath="/etc/oo"
 # ==================================================================================
-
+# In oo, only valid users can run scripts. So, you can only have subdirectories
+# in the base output directory which are from a valid user. The same applies to the
+# etc directories. oocd checks if the directories are from valid users, and if not, 
+# it will delete it, and exits with return code 1.
+# Otherwise it will exits with 0.
 # ===========================================================================
 # Don't change anything below this line unless you know what you are doing. =
 # ===========================================================================
@@ -26,10 +30,10 @@ if [[ -z "$oo_logbasepath" \
 fi
 
 oo_temp_logfile=$(mktemp)
-oo_deleted_dirs=0
-
+oo_deleted_var_dirs=0
+oo_deleted_etc_dirs=0
 {
-# loop through the directories
+# loop through the var directories
 for oocd_directory in $oo_logbasepath/*
 do
   if [[ -d $oocd_directory ]]; then
@@ -37,7 +41,21 @@ do
     if [[ -z "$(getent passwd $oocd_userdir)" ]]; then
       # delete directory of non existent user
       echo "Deleting "$oocd_directory" ..."
-      (( oo_deleted_dirs++ ))
+      (( oo_deleted_var_dirs++ ))
+      rm -rf "$oocd_directory"
+    fi
+  fi
+done
+
+# loop through the etc directories
+for oocd_directory in $oo_confpath/users.conf/*
+do
+  if [[ -d $oocd_directory ]]; then
+    oocd_userdir=`basename "$oocd_directory"`
+    if [[ -z "$(getent passwd $oocd_userdir)" ]]; then
+      # delete directory of non existent user
+      echo "Deleting "$oocd_directory" ..."
+      (( oo_deleted_etc_dirs++ ))
       rm -rf "$oocd_directory"
     fi
   fi
@@ -46,3 +64,9 @@ done
 
 cat $oo_temp_logfile
 rm -f $oo_temp_logfile
+
+if [[ $oo_deleted_var_dirs -ne 0 || $oo_deleted_etc_dirs -ne 0 ]]; then
+  exit 1
+else
+  exit 0
+fi
diff --git a/oohk b/oohk
--- a/oohk
+++ b/oohk
@@ -7,7 +7,12 @@
 # The quotes are needed in case there are spaces in the directory name.            =
 oo_confpath="/etc/oo"
 # ==================================================================================
-
+# The housekeeping job oohk checks all the output directories and files. It will
+# delete expired output files and empty directories. It will also check if the
+# expiration date is valid. If not, the file will also be deleted (and the filename
+# will be printed.
+# oohk exits with return code 1 when there were invaliddates detected, otherwise
+# it exits with 0.
 # ===========================================================================
 # Don't change anything below this line unless you know what you are doing. =
 # ===========================================================================
@@ -118,3 +123,9 @@ echo "Total empty directories: ""$oo_totalemptydirs"
 } >"$oo_reportfile"
 cat "$oo_reportfile"
 rm -f "$oo_reportfile"
+
+if [[ $oo_totalinvaliddates -eq 0 ]]; then
+  exit 0
+else
+  exit 1
+fi
diff --git a/oorp b/oorp
--- a/oorp
+++ b/oorp
@@ -7,7 +7,10 @@
 # The quotes are needed in case there are spaces in the directory name.            =
 oo_confpath="/etc/oo"
 # ==================================================================================
-
+# oorp checks the return code of the scripts which ran under control of oo and
+# reports it.
+# oorp exits with 1 of it finds a return code not equal to 0, otherwise it exits
+# with 0.
 # ===========================================================================
 # Don't change anything below this line unless you know what you are doing. =
 # ===========================================================================
@@ -84,6 +87,7 @@ do
               #echo "oo_resultcode: $oo_resultcode"
               if [[ "$oo_resultcode" -ne "0" ]]; then
                 (( oo_totalfiles_resultcode++ ))
+                oo_result_code=1
                 (( oo_dirfiles_resultcode++ ))
                 (( oo_userfiles_resultcode++ ))
                 oo_scriptnameline=`sed -n '5p' "$oo_file"`
@@ -112,3 +116,9 @@ cat "$oo_reportfile"
 
 rm -f "$oo_reportfile"
 rm -f "$oo_temp_user_output"
+
+if [[ $oo_totalfiles_resultcode -eq 0 ]]; then
+  exit 0
+else
+  exit 1
+fi
